### ISSUE TITLE
Features für die Seite. 

### ISSUE THREAD

**Issue by jani270** [DerDomee/skyblock-stats#2]
Hi :3 
Hier mal paar Ideen für die Website.

1.  Missing Accessories:
Wie der Name schon sagt zeigt es die Missing Accessories von einem Spieler als Menu unter den Inactive Accessories. (Wie bei den Missing Pets)

2.  Skillrechner: 
Für die faulen Leute unter den Spielern ein Rechner als Extra "Tab" oder oben bei den Skills, der bei Alchemy und Enchanting die Kosten und Materialien zum maxen vom Skill anzeigt.

3. Petinformationen:
Anzeigen was das Pet kann wie im Screenshot unten gezeigt.

[![image](https://user-images.githubusercontent.com/69345714/89632187-1bbe9d80-d8a2-11ea-85f5-f53a3f290d6b.png)
](url)

Hoffe davon bekommt du was hin :P

**Comment by DerDomee** [comment]
1. see #3 
2. won't add, there are already working solutions for this
3. see #4
