### ISSUE TITLE
Show pet skills and stats

### ISSUE THREAD

**Issue by DerDomee** [DerDomee/skyblock-stats#4]
On owned pets, show stats and skills in addition to current XP

Related to #2 , third idea

**Comment by DerDomee** [comment]
This might be fixed now. Issue stays open until there are no more bug reports relating to this

**Comment by DerDomee** [comment]
No more stat and ability issues found. Closing.

**Comment by b1n4ryj4n** [comment]
Hound Pet ability stats are still wrong. max 'Scavenger' gain is +5 coins per monster kill at level 100. 

Prof. my lvl 62 Hound gains ingame only +3.1 coins and on your stats website +30.3 coins.

![derdom se - hound](https://user-images.githubusercontent.com/3122325/92090468-bf329d80-edcf-11ea-8286-e2fb6e7e6752.png)
![ingame - hound](https://user-images.githubusercontent.com/3122325/92090474-c0fc6100-edcf-11ea-8f5c-d6bce68d3dee.png)

**Comment by DerDomee** [comment]
> Hound Pet ability stats are still wrong. max 'Scavenger' gain is +5 coins per monster kill at level 100.

This is now fixed with a76373d
Just a small typo, forgot a leading zero.
