### ISSUE TITLE
Mongo Error on entering a username

### ISSUE THREAD

**Issue by Redst0neFlux** [DerDomee/skyblock-stats#6]
**Describe the bug**
When I search for a user, the site displays "MongoError: text index required for $text query"

**To Reproduce**
1. Go to https://sky.derdom.ee
2. Type in a username
3. See error

**Expected behavior**
My user profile is displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/69603438/96254668-9516f280-0fad-11eb-8441-f5f9cdf5faae.png)

**Used device (if applicable please complete the following information):**
 - OS: Windows
 - Chrome
 - sky.derdom.ee

**Additional context**
N/A

**Comment by DerDomee** [comment]
Known bug and there is already a workaround for that. If this error occures, just try again in a few (up to 30) Minutes, then everything works again.

I wont fix this anyway, as I discontinued this project. use https://sky.shiiyu.moe instead.
